apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: pod-1
spec:
  affinity: #指定したnodeにpod生成
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: ds 
            operator: In
            values:
            - send
  containers: #使用するコンテナイメージ指定
  - name: pod-1
    image: saiga1001/image-13:1.0
    resources: #リソース指定
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8010
---
apiVersion: v1
kind: Service
metadata:
  name: pod-1-service #サービス作成
spec:
  selector:
    app: pod-1
  ports:
  - protocol: TCP
    port: 8010 #サービス自体のport
    targetPort: 8010 #pod内のコンテナのport