apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: pod-2
spec:
  affinity: #指定したnodeにpod生成
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dp1
            operator: In
            values:
            - pre1
  containers: #使用するコンテナイメージ指定
  - name: pod-2
    image: saiga1001/image-23:1.0
    resources: #リソース指定
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8020
---
apiVersion: v1
kind: Service
metadata:
  name: pod-2-service #サービス作成
spec:
  selector:
    app: pod-2 #pod指定
  ports:
  - protocol: TCP
    port: 8020 #サービス自体のport
    targetPort: 8020 #pod内のコンテナのport
